### ISSUE TITLE
Short key assignments depend from input language

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#104]
There some glitches on using key assignments with different keyboard input languages.
When I use Ukrainian its impossible use key <kbd>]</kbd> for lock point, but with English or Russian keyboard input language this work.
Think, for short keys need parse key codes and NOT key events or characters that depend from current keyboard language layout.
![IBM keyboard codes](http://www.ibm.com/support/knowledgecenter/api/content/nl/ru/ssw_aix_61/com.ibm.aix.keyboardtechref/doc/kybdtech/figures/kybdt1.jpg)

**Comment by whitequark** [comment]
No, scancodes are not a right solution. Using scancodes will break keyboard accelerators for users with alternative Latin layouts (such as English/German, with German having y instead of z) and Dvorak layouts and so on.

Anyway, SolveSpace does not handle keyboard accelerators itself, it relies on the platform GUI libraries. So, this is a problem with GTK2, not SolveSpace, and will exhibit in all GTK2 apps. You can try building SolveSpace with GTK3 (use `cmake -DGUI=gtk3` in [build steps]( https://github.com/whitequark/solvespace#building-for-linux)).
