### ISSUE TITLE
Allow use internal "plotter-style" font for TrueType Text. 

### ISSUE THREAD

**Issue by Symbian9** [whitequark/solvespace#165]
Please, make it possible use internal SolveSpace font for TrueType text blocks.

P.S.: I start think about it when cant rotate comment text (maybe you soon can allow rotating future for comments too).

**Comment by Evil-Spirit** [comment]
rotating for comments is supported, you need to create custom style and assign it to comment. you can choose text options for custom style.

**Comment by Symbian9** [comment]
Is "TrueType font text" allow plotter fonts? (single line without fill)

**Comment by whitequark** [comment]
@Symbian9 The TrueType renderer does not care about filling, it is implicit in TrueType, with the same behavior as SolveSpace sketches (outermost space is unfilled and then it alternates). So if you use a plotter-style font you'll get a broken sketch, because you can't do what you want with entities at all.

**Comment by whitequark** [comment]
What is the purpose of using plotter font for text entities?

**Comment by Evil-Spirit** [comment]
@Symbian9, there is no point to use true type as plotter. true type is for building 3d font objects, so it need to have closed contours for each glyph. for the poltter there is comment.
