### ISSUE TITLE
Parametric sketches (i.e. adjustable by changing variables)

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#194]
That is, sketches that include an adjustable parameter table.

**Comment by Evil-Spirit** [comment]
For this, we sould introduce parameter table for the sketch.
For each parameter:
* value
* name
* "free" or "variable" - ability to solve it through solver (otherwise, this is just constant).
* min, max (for ranged variable parameters)

For defining, we can use parameter table, or just type new name inside text input field of constraint:

![2016-06-01 13 31 20](https://cloud.githubusercontent.com/assets/1980537/15701621/2f5facf8-27fd-11e6-823e-1971ab1477c3.png)

**Comment by jasonk** [comment]
It would be also be awesome if you could have multiple sets of parameters and be able to switch between them.  So, for example, in addition to the regular settings, I could switch to a set of parameters that changes the spacing between assemblies, so I could easily switch back and forth between a normal assembled view and an exploded view.

**Comment by whitequark** [comment]
Yeah, that's planned. Though exploded view is a separate feature.

**Comment by ryannining** [comment]
i change some code, using `comment` on constraint to keep the expresion editable.

And then i use `constraint comment` to introduce named variable (parsing `=` and save to MAP). 

Just the problem is, when file is saved then loaded, the named variable is not loaded, need to edit comment and immidiately press return to process the expression.

![Imgur]
(http://i.imgur.com/bDDEuYL.png))

**Comment by whitequark** [comment]
Migrated to solvespace/solvespace
